In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv('train.csv')

In [4]:
data.fillna(0,inplace = True)

In [5]:
data.head()

id  perc_premium_paid_by_cash_credit  age_in_days  Income  \
0  110936                             0.429        12058  355060   
1   41492                             0.010        21546  315150   
2   31300                             0.917        17531   84140   
3   19415                             0.049        15341  250510   
4   99379                             0.052        31400  198680   

   Count_3-6_months_late  Count_6-12_months_late  \
0                    0.0                     0.0   
1                    0.0                     0.0   
2                    2.0                     3.0   
3                    0.0                     0.0   
4                    0.0                     0.0   

   Count_more_than_12_months_late  application_underwriting_score  \
0                             0.0                           99.02   
1                             0.0                           99.89   
2                             1.0                           98.69   
3                             0.0                           99.57   
4                             0.0                           99.87   

   no_of_premiums_paid sourcing_channel residence_area_type  premium  target  
0                   13                C               Urban     3300       1  
1                   21                A               Urban    18000       1  
2                    7                C               Rural     3300       0  
3                    9                A               Urban     9600       1  
4                   12                B               Urban     9600       1

In [6]:
data = pd.get_dummies(data)

In [7]:
test = pd.read_csv('test.csv')

In [8]:
test.fillna(0, inplace = True)

In [9]:
test = pd.get_dummies(test)

In [10]:
data.head()

id  perc_premium_paid_by_cash_credit  age_in_days  Income  \
0  110936                             0.429        12058  355060   
1   41492                             0.010        21546  315150   
2   31300                             0.917        17531   84140   
3   19415                             0.049        15341  250510   
4   99379                             0.052        31400  198680   

   Count_3-6_months_late  Count_6-12_months_late  \
0                    0.0                     0.0   
1                    0.0                     0.0   
2                    2.0                     3.0   
3                    0.0                     0.0   
4                    0.0                     0.0   

   Count_more_than_12_months_late  application_underwriting_score  \
0                             0.0                           99.02   
1                             0.0                           99.89   
2                             1.0                           98.69   
3                             0.0                           99.57   
4                             0.0                           99.87   

   no_of_premiums_paid  premium  target  sourcing_channel_A  \
0                   13     3300       1                   0   
1                   21    18000       1                   1   
2                    7     3300       0                   0   
3                    9     9600       1                   1   
4                   12     9600       1                   0   

   sourcing_channel_B  sourcing_channel_C  sourcing_channel_D  \
0                   0                   1                   0   
1                   0                   0                   0   
2                   0                   1                   0   
3                   0                   0                   0   
4                   1                   0                   0   

   sourcing_channel_E  residence_area_type_Rural  residence_area_type_Urban  
0                   0                          0                          1  
1                   0                          0                          1  
2                   0                          1                          0  
3                   0                          0                          1  
4                   0                          0                          1

In [14]:
x.head()

id  perc_premium_paid_by_cash_credit  age_in_days  Income  \
0  110936                             0.429        12058  355060   
1   41492                             0.010        21546  315150   
2   31300                             0.917        17531   84140   
3   19415                             0.049        15341  250510   
4   99379                             0.052        31400  198680   

   Count_3-6_months_late  Count_6-12_months_late  \
0                    0.0                     0.0   
1                    0.0                     0.0   
2                    2.0                     3.0   
3                    0.0                     0.0   
4                    0.0                     0.0   

   Count_more_than_12_months_late  application_underwriting_score  \
0                             0.0                           99.02   
1                             0.0                           99.89   
2                             1.0                           98.69   
3                             0.0                           99.57   
4                             0.0                           99.87   

   no_of_premiums_paid  sourcing_channel_A  sourcing_channel_B  \
0                   13                   0                   0   
1                   21                   1                   0   
2                    7                   0                   0   
3                    9                   1                   0   
4                   12                   0                   1   

   sourcing_channel_C  sourcing_channel_D  sourcing_channel_E  \
0                   1                   0                   0   
1                   0                   0                   0   
2                   1                   0                   0   
3                   0                   0                   0   
4                   0                   0                   0   

   residence_area_type_Rural  residence_area_type_Urban  
0                          0                          1  
1                          0                          1  
2                          1                          0  
3                          0                          1  
4                          0                          1

In [12]:
x = data.drop('target', axis = 1)
x = x.drop('premium', axis = 1)

y = data['target']

In [16]:
x.head()

perc_premium_paid_by_cash_credit  age_in_days  Income  \
0                             0.429        12058  355060   
1                             0.010        21546  315150   
2                             0.917        17531   84140   
3                             0.049        15341  250510   
4                             0.052        31400  198680   

   Count_3-6_months_late  Count_6-12_months_late  \
0                    0.0                     0.0   
1                    0.0                     0.0   
2                    2.0                     3.0   
3                    0.0                     0.0   
4                    0.0                     0.0   

   Count_more_than_12_months_late  application_underwriting_score  \
0                             0.0                           99.02   
1                             0.0                           99.89   
2                             1.0                           98.69   
3                             0.0                           99.57   
4                             0.0                           99.87   

   no_of_premiums_paid  sourcing_channel_A  sourcing_channel_B  \
0                   13                   0                   0   
1                   21                   1                   0   
2                    7                   0                   0   
3                    9                   1                   0   
4                   12                   0                   1   

   sourcing_channel_C  sourcing_channel_D  sourcing_channel_E  \
0                   1                   0                   0   
1                   0                   0                   0   
2                   1                   0                   0   
3                   0                   0                   0   
4                   0                   0                   0   

   residence_area_type_Rural  residence_area_type_Urban  
0                          0                          1  
1                          0                          1  
2                          1                          0  
3                          0                          1  
4                          0                          1

In [15]:
x = x.drop('id', axis = 1)

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
logg = LogisticRegression()

In [19]:
logg.fit(x,y)

/home/ahtrahdis_7/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [23]:
xtest.shape

(34224, 15)

In [21]:
xtest = test.drop('id', axis = 1)

In [25]:
predict = logg.predict(xtest)


In [26]:
predict

array([1, 1, 1, ..., 1, 1, 1])

In [25]:
logg.score(x,y)

0.937409990858202

In [39]:
res = test['id']

In [33]:
predict

array([1, 1, 1, ..., 1, 1, 1])

In [35]:
d = pd.read_csv('ss.csv')

In [36]:
d.head()

id  target
0    649     0.5
1  81136     0.5
2  70762     0.5
3  53935     0.5
4  15476     0.5

In [37]:
print(predict.T)

[1 1 1 ... 1 1 1]


In [46]:
import csv

In [27]:
sub3 = pd.DataFrame()
    

In [29]:
sub3['target'] = predict

In [30]:
res3 = pd.concat([test['id'], sub3], axis = 1)

In [32]:
res3.to_csv('res3.csv', header = 'True', index = 'False')